### PR TITLE
Choose a random date of birth

### PR DESCRIPTION
**Pull request by sLoPPydrive**
Most requested and most criticised feature: Date of birth was fixed. Now it is random.

### CODE REVIEW

**Comment by drallieiv** [comment]
The thing is that it would be better if the birth date used will change things (I dont have a detailed list) wether the birth date gets considered as an adult or a child.

The activation mail is not identical, I'm pretty sure an underage account can add child accounts on his own. It should either be by default, or with a config flag activating or not "adult only" constrain.

Current fixed DOB is always an adult.

Also, Kinan is already using Apache Commons Lang, so you have RandomStringUtils at your disposal, wich gives a set of random functions.

Also using a real date time format (such as LocalDateTime) would be easier to avoid having to manage manually limit cases (leap years, leap seconds, febuary, and such).

Just start with a base date, and add or remove a random amount of seconds or milliseconds.

**Comment by drallieiv** [comment]
After re-checking, the date is indeed bounded between and 1970 to 2000, but 2000 is not based on current time, so with an absolute limit, it will shift with the years passing by.

Also a unit test might be nice, but I could do without it.

**Comment by elincognito** [comment]
@drallieiv  Thing is fixed DOB is asking for easy Ban/Warn :p 
Looking foward for this PR to be merged. 
Good job

**Comment by drallieiv** [comment]
I'll merge that and refactor later

**Pull request merged**
