### PR TITLE
Adding script to resend validation emails

### PR DESCRIPTION
**Pull request by gustavo-momente**

### CODE REVIEW

**Comment by drallieiv** [comment]
As it does not share anything with kinan, it would better be as a separate project.
But I can add a link to it in the readme documentation.

**Comment by drallieiv** [comment]
The place to be if you want to add it as integrated part of kinan would be in https://github.com/drallieiv/KinanCity/tree/develop/ptc-api

plus some kind of command line interface submodule.

**Comment by gustavo-momente** [comment]
I'll try to integrate it to ptc-api them.

**Comment by M3G4THEKING** [comment]
Even if this is nothing related with kinan project @drallieiv  need to say, this is working 100% i have made a full test, thanks for this code @gustavo-momente .

**Comment by ckiddtilley** [comment]
@gustavo-momente I cannot get this to work at all. I've installed the requirements.txt and when i run the .py it goes through all the motions, the progress bar completes but no emails are received.

**Comment by gustavo-momente** [comment]
@ckiddtilley I'll have to check this weekend and will report back, maybe they changed something in the api

**Comment by wickles** [comment]
Works fine, thanks. Should be a separate project probably.

**Pull request closed without merging**
